name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
- title: 'Features'
  labels:
  - 'feature'
  - 'enhancement'
  - 'dockerfiles'
- title: 'Bug Fixes'
  labels:
  - 'fix'
  - 'bugfix'
  - 'bug'
- title: 'Maintenance'
  labels:
  - 'chore'
  - 'dependencies'
  - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
    - 'major'
  minor:
    labels:
    - 'minor'
  patch:
    labels:
    - 'patch'
  default: patch
exclude-labels:
- 'skip-changelog'
autolabeler:
- label: 'dockerfile'
  files:
  - '/**/Dockerfile'
- label: 'documentation'
  files:
  - '**/*.md'
  branch:
  - '/docs{0,1}\/.+/'
- label: 'bug'
  branch:
  - '/fix\/.+/'
  title:
  - '/fix/i'
- label: 'enhancement'
  branch:
  - '/feature\/.+/'
  body:
  - '/JIRA-[0-9]{1,4}/'
template: |
  ## Changes
  $CHANGES
