name: Build and Publish Dev Docker Image

on:
  push:
    branches:
    - main
    paths:
    - 'dev/Dockerfile'
  pull_request_target:
    paths:
    - 'dev/Dockerfile'
  workflow_dispatch:

jobs:
  buildAndPush:
    uses: ./.github/workflows/publish-docker.yaml
    with:
      image: dev
