name: Build and Publish Net Docker Image

on:
  push:
    branches:
    - main
    tags:
    - v*
    paths:
    - 'net/Dockerfile'
  pull_request_target:
    paths:
    - 'net/Dockerfile'
  workflow_dispatch:

jobs:
  buildAndPush:
    uses: ./.github/workflows/publish-docker.yaml
    with:
      image: net
