name: Build and Publish Net Docker Image

on:
  push:
    branches:
    - main
    tags:
    - v*
    paths:
    - 'net/Dockerfile'
  pull_request_target:
    paths:
    - 'net/Dockerfile'
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'Build and Publish Base Docker Image'
    branches-ignore:
      - 'feature/**'
      - 'fix/**'
      - 'bugfix/**'
    types:
      - completed

jobs:
  buildAndPush:
    uses: ./.github/workflows/publish-docker.yaml
    with:
      image: net
